package com.codekrypt.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.codekrypt.greendao.db.LOG;

import com.codekrypt.greendao.db.LOGDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lOGDaoConfig;

    private final LOGDao lOGDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lOGDaoConfig = daoConfigMap.get(LOGDao.class).clone();
        lOGDaoConfig.initIdentityScope(type);

        lOGDao = new LOGDao(lOGDaoConfig, this);

        registerDao(LOG.class, lOGDao);
    }
    
    public void clear() {
        lOGDaoConfig.clearIdentityScope();
    }

    public LOGDao getLOGDao() {
        return lOGDao;
    }

}
