package ca.bcit.comp3717.a00950911.opendata.dao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CATEGORY".
 */
@Entity
public class Category {

    @Id
    private Long id;

    @NotNull
    private String cat_name;

    @Generated
    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    @Generated
    public Category(Long id, String cat_name) {
        this.id = id;
        this.cat_name = cat_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getCat_name() {
        return cat_name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setCat_name(@NotNull String cat_name) {
        this.cat_name = cat_name;
    }

}
