package ca.bcit.comp3717.a00950911.opendata.dao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig datasetDaoConfig;

    private final CategoryDao categoryDao;
    private final DatasetDao datasetDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        datasetDaoConfig = daoConfigMap.get(DatasetDao.class).clone();
        datasetDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        datasetDao = new DatasetDao(datasetDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Dataset.class, datasetDao);
    }

    public void clear() {
        categoryDaoConfig.clearIdentityScope();
        datasetDaoConfig.clearIdentityScope();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public DatasetDao getDatasetDao() {
        return datasetDao;
    }

}
